---
language: node_js
services:
    - docker
before_script:
    - docker build --tag expo_image .
script:
    - docker run -it -v $(pwd):/usr/src/app -P --network="host" expo_image "npm install && expo login && expo build:android"
