---
language: node_js
services:
    - docker
before_install:
    - docker build --tag expo_image .
    - docker run -itd -v $(pwd):/usr/src/app --name expo_container expo_image bash
install:
    - docker exec expo_container npm install
before_script:
    - docker exec expo_container expo login
script:
    - docker exec expo_container expo build:android
    - docker exec expo_container expo url:apk
after_script:
    - docker stop expo_container
