---
language: node_js
services:
    - docker
install:
    - docker build --tag expo_image .
    - docker run -it -v $(pwd):/usr/src/app -P --network="host" expo_image
before_script:
    - expo login
script:
    - expo build:android
    - expo url:apk