---
language: node_js
if: branch = master
services:
    - docker
before_install:
    - docker build --tag expo_image .
    - docker run -itd -v $(pwd):/usr/src/app -e EXPO_CLI_USERNAME=$(EXPO_CLI_USERNAME) -e EXPO_CLI_PASSWORD=$(EXPO_CLI_PASSWORD) --name expo_container expo_image bash
install:
    - docker exec expo_container npm install
before_script:
    - docker exec expo_container expo login
script:
    - docker exec expo_container expo build:android --no-wait -t apk
after_script:
    - docker stop expo_container
