---
language: node_js
branches:
    only:
        - master
        - development
services:
    - docker
before_install:
    - docker build --tag expo_image .
    - docker run -itd -v $(pwd):/usr/src/app --env EXPO_CLI_PASSWORD --env EXPO_CLI_USERNAME --name expo_container expo_image bash
install:
    - docker exec expo_container npm install
script:
    - docker exec expo_container expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD
deploy:
    - provider: script
      script:
          docker exec expo_container expo publish --non-interactive --max-workers 1 --release-channel prod
      on:
          branch: master
    - provider: script
      script:
          docker exec expo_container expo publish --non-interactive --max-workers 1 --release-channel staging
      on:
          branch: development
