---
language: node_js
services:
    - docker
before_script:
    - docker build --tag expo_image .
    - docker run -d -v $(pwd):/usr/src/app --name expo_container expo_image bash
    - docker exec expo_container npm install
script:
    - docker exec expo_container expo login
    - docker exec expo_container expo build:android
    - docker exec expo_container expo url:apk
after_script:
    - docker stop expo_container
